[api]
enabled = true
port = 54321

[auth]
enabled = true
additional_redirect_urls = ["http://localhost:5173", "http://localhost:5174", "http://localhost:5175", "http://localhost:5176"]

[edge_functions]
enabled = true
